variables:
  STACK_FILE: "/root/docker/inhouse_projects/micofrontend-poc/my-first-app/docker-compose.yml"
  CODE_DIR: "/root/docker/inhouse_projects/micofrontend-poc/my-first-app/app/code"

before_script:
  - echo "Runner started"

stages:
  - Test
  - devBuild
  - devDeploy

Sonarqube-Check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    GIT_DEPTH: 0
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
      - .scannerwork
  stage: Test
  script: 
    - sonar-scanner -Dsonar.projectKey=$SONAR_TOKEN  -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -D sonar.projectName=$CI_PROJECT_NAME -Dsonar.qualitygate.wait=true -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.sourceEncoding=UTF-8  
  allow_failure: true
  only:
    - module-federation-POC
  tags:
   - pacewisdom-docker-shared-runner


devBuild:
  stage: devBuild
  variables:
    CI_COMMIT_REF_NAME:  module-federation-POC
  script:
    - echo "Deploying in https://micofrontend-my-first-app.pacewisdom.in"
    - rsync -ravz --exclude '.git/' ./ $CODE_DIR/ --delete
    - docker compose -f $STACK_FILE build
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://micofrontend-my-first-app.pacewisdom.in
  only:
    - module-federation-POC
  tags:
    - inhouse-runner2
  allow_failure: false

devDeploy:
  stage: devDeploy
  variables:
    CI_COMMIT_REF_NAME:  module-federation-POC
  script:
    - echo "Deployment started..."
    - docker compose -f $STACK_FILE up -d
    - docker exec proxy_server nginx -s reload
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://micofrontend-my-first-app.pacewisdom.in
  only:
    - module-federation-POC
  tags:
    - inhouse-runner2
  allow_failure: false

